lsi: false
safe: true
domain: cbart.github.io
url: https://cbart.github.io/learning
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: cayman
