lsi: false
safe: true
domain: cbart-learning.github.io
url: https://cbart-learning.github.io
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: cayman
