lsi: false
safe: true
domain: learning.cbart.github.io
url: https://learning.cbart.github.io
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: cayman
